# https://travis-ci.org/peterbe/premailer

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

before_install:
  - pip install coverage

install:
  - python setup.py install
  - pip install tox coveralls

env:
  - TOX_ENV=flake8
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy

script:
  - tox -e $TOX_ENV

after_success:
  # Report coverage results to coveralls.io
  - coveralls

deploy:
  provider: pypi
  user: peterbe
  password:
    secure: mdzD1SHDQ84ZK8tVXdF2LuMsws7it/7foompnuNUTQSVaKdjaHpwTYQtmdLUX0Jv54Plx4861GWNf6CD5IVfU7G8R2Ls/5/tQECFG01AspGz23lL1PxUg9tpNm+LPkQtkJzvS3f4i6/mODnKcoaSnhL63JuGaUNa72B1yBaN4hY=
  on:
    repo: peterbe/premailer
  distributions: "sdist bdist_wheel"
